CREATE DATABASE IF NOT EXISTS NYC_TAXI_DW;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DW.RAW;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DW.TRANSFORM;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DW.MARTS;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE DATABASE NYC_TAXI_DW;
USE SCHEMA RAW;

CREATE FILE FORMAT IF NOT EXISTS PARQUET_FORMAT
    TYPE = PARQUET
    USE_VECTORIZED_SCANNER = TRUE;

CREATE STAGE IF NOT EXISTS NYC_TAXI_STAGE
    FILE_FORMAT = PARQUET_FORMAT;

CREATE TABLE IF NOT EXISTS YELLOW_TAXI_TRIPS (
    src VARIANT,
    source_file STRING,
    source_row_number NUMBER,
    loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
